### ISSUE TITLE
Appcenter.ms: Illegal character '?' NKVPhonePicker/Sources/Bundle/Countries.bundle/Images/?.png

### ISSUE THREAD

**Issue by ARGAMX** [NikKovIos/NKVPhonePicker#35]
## General Information

* NKVPhonePicker Version:
1.1.0
* Swift Version:
4.1

##  What happened?

Trying to make a build of app on the **appcenter.ms** got that error:

> Start uploading file 'build/Robomed.xcarchive/Products/Applications/Robomed.app/Frameworks/NKVPhonePicker.framework/Countries.bundle/Images/?.png' to server, chunk '1'.
Chunk '1' attempt '2' of file 'build/Robomed.xcarchive/Products/Applications/Robomed.app/Frameworks/NKVPhonePicker.framework/Countries.bundle/Images/?.png' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Wildcards are not allowed. ---> Microsoft.TeamFoundation.InvalidPathException: Wildcards are not allowed.
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__16.MoveNext().
##[error]File upload failed even after retry.

http://joxi.ru/LmGeNNPiwep6nA

Deleted the NKVPhonePicker from the project and build success.
So the problem is files with '?' in name, which is not supported by Microsoft file systems 👎

## What did you expect to happen?

Success build without deleting NKVPhonePicker from the project.

**Comment by ARGAMX** [comment]
https://github.com/NikKovIos/NKVPhonePicker/pull/36

**Comment by NikKovIos** [comment]
Merged! Thanks again!
